export interface ReportGenerationParams {
    patientName: string;
    patientId: string;
    scanType: string;
    condition: string;
    confidence: number;
    explanation: string;
    reportDate: string;
  }
  
  export const generateReport = ({ 
    patientName, 
    patientId, 
    scanType, 
    condition, 
    confidence, 
    explanation,
    reportDate
  }: ReportGenerationParams) => {
    const date = new Date(reportDate);
    const formattedDate = date.toLocaleDateString('en-US', {
      year: 'numeric', 
      month: 'long', 
      day: 'numeric'
    });
    const formattedTime = date.toLocaleTimeString('en-US', {
      hour: '2-digit', 
      minute: '2-digit'
    });
  
    if (scanType === 'chest') {
      return `
  # RADIOLOGICAL REPORT
  
  ## PATIENT INFORMATION
  - **Patient Name:** ${patientName}
  - **Patient ID:** ${patientId}
  - **Exam Date:** ${formattedDate} at ${formattedTime}
  - **Exam Type:** Chest X-Ray
  - **Referring Physician:** N/A
  
  ## CLINICAL INDICATION
  Routine chest X-ray examination for pneumonia screening.
  
  ## FINDINGS
  ${explanation || `
  Analysis of the chest X-ray shows ${condition === 'pneumonia' ? 'evidence of pneumonia' : 'no signs of pneumonia'}. ${condition === 'pneumonia' ? 'There are opacities consistent with pneumonic infiltrates.' : 'Lung fields appear clear.'} Heart size and pulmonary vascularity are within normal limits. No pleural effusion or pneumothorax is identified.`}
  
  ## IMPRESSION
  ${condition === 'pneumonia' 
    ? `POSITIVE FOR PNEUMONIA with ${(confidence * 100).toFixed(1)}% confidence.`
    : `NEGATIVE FOR PNEUMONIA with ${(confidence * 100).toFixed(1)}% confidence.`}
  
  ## RECOMMENDATIONS
  ${condition === 'pneumonia' 
    ? 'Clinical correlation and appropriate treatment for pneumonia is recommended. Follow-up imaging may be necessary to monitor response to treatment.'
    : 'No further imaging follow-up is required at this time based on these findings alone.'}
  
  Generated by ImageMedix AI Diagnostic System
  This report should be reviewed by a licensed healthcare professional.
      `;
    } else {
      return `
  # RADIOLOGICAL REPORT
  
  ## PATIENT INFORMATION
  - **Patient Name:** ${patientName}
  - **Patient ID:** ${patientId}
  - **Exam Date:** ${formattedDate} at ${formattedTime}
  - **Exam Type:** Brain MRI
  - **Referring Physician:** N/A
  
  ## CLINICAL INDICATION
  Brain MRI for evaluation of potential tumor.
  
  ## TECHNIQUE
  Standard multiplanar MRI sequences of the brain were performed.
  
  ## FINDINGS
  ${explanation || `
  Analysis of the brain MRI ${condition === 'tumor' ? 'reveals evidence of an intracranial mass' : 'shows no evidence of intracranial mass'}. ${condition === 'tumor' ? 'The lesion demonstrates characteristics consistent with a brain tumor.' : 'The brain parenchyma demonstrates normal signal intensity throughout.'} Ventricles and sulci are of normal size and configuration. No midline shift or mass effect is seen. No evidence of acute infarction, hemorrhage, or extra-axial collection.`}
  
  ## IMPRESSION
  ${condition === 'tumor' 
    ? `POSITIVE FOR BRAIN TUMOR with ${(confidence * 100).toFixed(1)}% confidence.`
    : `NEGATIVE FOR BRAIN TUMOR with ${(confidence * 100).toFixed(1)}% confidence.`}
  
  ## RECOMMENDATIONS
  ${condition === 'tumor' 
    ? 'Neurosurgical consultation is recommended. Consider additional imaging with contrast for further characterization. Clinical correlation is advised.'
    : 'No further imaging follow-up is required at this time based on these findings alone.'}
  
  Generated by ImageMedix AI Diagnostic System
  This report should be reviewed by a licensed healthcare professional.
      `;
    }
  };